# This is a basic workflow to help you get started with Actions

name: AzureAuthSample

# Controls when the workflow will run
on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Log in with Azure
        uses: azure/login@v1
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
      - name: Azure PowerShell Action
              uses: Azure/powershell@v1
              with:
                inlineScript: Get-AzVirtualNetwork -ResourceGroupName "Networking_RSG"
                azPSVersion: 3.1.0
