# This is a basic workflow to help you get started with Actions

name: AzureAuthSample

# Controls when the workflow will run
on:
  workflow_dispatch:

jobs:

  azureAuth:
    runs-on: ubuntu-latest
    steps:

    - name: Login via Az module
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
