# Basic workflow to deploy and configure a Linux VM to Azure with the LAMP stack

name: Deployment and Configuration of Azure VM

# Workflow Triggers: On push to main branch or manual execution via the Actions tab.
on:
  workflow_dispatch:

jobs:

# Deploy VM in Azure
  deployVM:
    runs-on: windows-latest
    
    steps:
      # Checkout Code
      - name: Checkout exercise repo
        uses: actions/checkout@v2
               
      - name: Authenticate to Azure
        uses: azure/login@v1
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
          enable-AzPSSession: true
          
      - name: Deploy virtual machine in Azure
        uses: Azure/powershell@v1
              with:
              azPSVersion: 3.1.0
        run: IaC\Scripts\New-Deployment.ps1
