# Basic workflow to deploy and configure a Linux VM to Azure with the LAMP stack

name: Deployment and Configuration of Azure VM

# Declare variables
Env:
  ScriptsPath: '${{ env.GITHUB_WORKSPACE }}\IaC\Scripts'
  
# Workflow Triggers: On push to main branch or manual execution via the Actions tab.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
#  push:
#    branches: [ main ]

  workflow_dispatch:

jobs:

  # Deploy VM in Azure
  deployVM:
    runs-on: windows-latest
    
    steps:
      # Checkout Code
      - name: checkout exercise repo
        uses: actions/checkout@v2
        
      - name: set build script path
        run: |

          ls '${{ env.ScriptsPath'
      
      - name: deploy virtual machine in Azure
      
        env: 
          rsg:
          region:
          vmname:
          adminuser:
          
        run: >
          powershell -command "& '${{ env.ScriptsPath }}\New-LAMPVM.ps1'"
          -servicePrincipal ${{ secrets.SERVICE_PRINCIPAL_APPID }}
          -servicePrincipalSecret ${{ secrets.SERVICE_PRINCIPAL_SECRET }}
          -servicePrincipalTenantId ${{ secrets.SERVICE_PRINCIPAL_TENANTID }}
          -azureSubscriptionName ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          -resourceGroupName %rsg%
          -resourceGroupNameRegion %region%
          -serverName %vmname%
          -adminLogin %adminuser%
          -adminPassword ${{ secrets.ADMIN_PASSWORD }}

# DEFAULTS -- REMOVE WHEN DONE
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
