# Basic workflow to deploy and configure a Linux VM to Azure with the LAMP stack

name: Deployment and Configuration of Azure VM

# Workflow Triggers: On push to main branch or manual execution via the Actions tab.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
#  push:
#    branches: [ main ]

  workflow_dispatch:

jobs:

  # Deploy VM in Azure
  deployVM:
    runs-on: windows-latest
    
    steps:
      # Checkout Code
      - name: checkout exercise repo
        uses: actions/checkout@v2
        
      - name: set build script path
        run: |

          ls '${{ env.GITHUB_WORKSPACE }}\IaC\Scripts'
      - name: Authenticate to Azure
        uses: azure/login@v1
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
          enable-AzPSSession: true
      
      - name: deploy virtual machine in Azure
        uses: Azure/powershell@v1
          
        run: >
          powershell -command "& '${{ env.ScriptsPath }}\New-Deployment.ps1'"
